# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HexMonad Blog
author: HexMonad
author_avatar: https://gravatar.com/avatar/c28969c60b32b0220f5a958928b7b379?s=80
email: hexmonad@gmail.com
description: Blog about whatever.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://hexmonad.github.io"
#twitter_username: foo_bar
#github_username: foo_bar
github_repo: hexmonad
#google_analytics: UA-80085-YOUR-ID
# disqus: disqus-id

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap